openapi: 3.0.3
info:
  version: 1.694.0
  title: Windmill admin favorite API
  contact:
    name: Windmill Team
    email: contact@windmill.dev
    url: https://windmill.dev
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://windmill.dev/img/windmill.svg
servers:
- url: /api
security:
- bearerAuth: []
- cookieAuth: []
tags:
- name: favorite
paths:
  /w/{workspace}/favorites/star:
    post:
      summary: Star Item
      operationId: star
      tags:
      - favorite
      parameters:
      - $ref: '#/components/parameters/WorkspaceId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                favorite_kind:
                  type: string
                  enum:
                  - flow
                  - app
                  - script
                  - raw_app
                  - asset
      responses:
        '200':
          description: star item
  /w/{workspace}/favorites/unstar:
    post:
      summary: Unstar Item
      operationId: unstar
      tags:
      - favorite
      parameters:
      - $ref: '#/components/parameters/WorkspaceId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                favorite_kind:
                  type: string
                  enum:
                  - flow
                  - app
                  - script
                  - raw_app
                  - asset
      responses:
        '200':
          description: unstar item
components:
  parameters:
    WorkspaceId:
      name: workspace
      in: path
      required: true
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
externalDocs:
  description: documentation portal
  url: https://windmill.dev
